# Project information
site_name: Rincewind's Magic Luggage Full of Amiga Goodies
site_url: https://amiga-collection.org/
site_author: Rincewind
site_description: >-
  It's a magic luggage, full of Amiga goodies

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Open Sans
    code: Roboto Mono
#  logo: assets/images/logo.svg
#  favicon: assets/images/favicon.ico

# CSS overrides
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.saneheaders
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - smarty
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - glightbox:
      slide_effect: 'none'
      skip_classes:
        - skip-lightbox
  - redirects:
      redirect_maps:
        # Convenience redirects for top level sections (so for example
        # `/manual/` takes you to `manual/introduction/` instead of a 404).
        #
        'manual/index.md': 'manual/introduction.md'

        'games/e.md': 'games/e-f.md'
        'games/f.md': 'games/e-f.md'

        'games/g.md': 'games/g-j.md'
        'games/h.md': 'games/g-j.md'
        'games/i.md': 'games/g-j.md'
        'games/j.md': 'games/g-j.md'

        'games/k.md': 'games/k-l.md'
        'games/l.md': 'games/k-l.md'

        'games/m.md': 'games/m-o.md'
        'games/n.md': 'games/m-o.md'
        'games/o.md': 'games/m-o.md'

        'games/q.md': 'games/q-r.md'
        'games/r.md': 'games/q-r.md'

        'games/t.md': 'games/t-z.md'
        'games/u.md': 'games/t-z.md'
        'games/v.md': 'games/t-z.md'
        'games/w.md': 'games/t-z.md'
        'games/x.md': 'games/t-z.md'
        'games/y.md': 'games/t-z.md'
        'games/z.md': 'games/t-z.md'

# Page tree
nav:
  - Manual:
    - manual/index.md   # dummy page for redirecting

    - manual/introduction.md
    - manual/installation.md
    - manual/getting-started.md
    # - manual/on-crt-shaders.md
    - manual/input-handling.md
    - manual/hard-drive-games.md
    - manual/floppy-games.md
    - manual/cdtv-and-cd32-games.md
    - manual/save-states.md
    - manual/keyboard-shortcuts.md
    # - manual/folder-organisation.md
    - manual/customising-your-setup.md
    - manual/troubleshooting.md
    - manual/useful-websites.md
    - manual/thanks.md
    - manual/changelog.md
    # - manual/why-amiga-games.md

  - Game notes:
    - games/index.md
    - games/a.md
    - games/b.md
    - games/c.md
    - games/d.md
    - games/e-f.md
    - games/g-j.md
    - games/k-l.md
    - games/m-o.md
    - games/p.md
    - games/q-r.md
    - games/s.md
    - games/t-z.md

not_in_nav: |
  # To silence the warning about the custom `index.md` front page
  /index.md
